base_url: "https://atmfrontqa2.coonecta.com.ec/ExtremeWebTs"
timeout: 30000  # milisegundos
ignore_https_errors: true
users:
  admin:
    username: "205dnazareno"
    password: "P@sswo.2025++"
  tester:
    username: "205ccoro"
    password: "P@sswo.2025+*"
# Configura otras variables específicas del entorno QA según sea necesario